import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Toaster } from "sonner";
import { ShipmentIdProvider } from "@/components/hooks/useShipmentId";
import { ChakraProvider } from "@chakra-ui/react";
import SimulationProvider from "@/components/contexts/simulation-provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang='en'>
            <body className={inter.className}>
                <Toaster richColors />
                <ChakraProvider>
                    <ShipmentIdProvider>
                        <SimulationProvider>{children}</SimulationProvider>
                    </ShipmentIdProvider>
                </ChakraProvider>
            </body>
        </html>
    );
}
